version: "3.7"

services:
  prometheus:
    image: surenbaboyan/prometheus:${Prometheus_Version}
    container_name: prometheus
    ports:
      - 9190:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
    - monitoring
  
  node-exporter:
    image: surenbaboyan/node_exporter:${Node_Exporter_Version}
    container_name: node-exporter
    ports: 
      - 9200:9100
    networks:
      - monitoring
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${Cadvisor_Version}
    container_name: cadvisor
    ports:
      - 8180:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3002:3000
    #environment:
     # - GF_SECURITY_ADMIN_PASSWORD=Admin1324
      #- GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafanaCfg:/etc/grafana/provisioning/
    networks:
      - monitoring
    

volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  monitoring:
    driver: bridge