- hosts: 'ec2'
  tasks:
   - name: Create network
     docker_network:
      name: '{{ ZABBIX_NETWORK_NAME }}'
      appends: yes

   - name: Create mysql db
     docker_container:
      image: mysql:{{ MY_SQL_VERSION }}
      name: '{{ CONTAINER_NAME_MY_SQL }}'
      state: started
      env:
       MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
       MYSQL_USER: '{{ MYSQL_USER }}'
       MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
       MYSQL_ROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
      networks:
       - name: '{{ ZABBIX_NETWORK_NAME }}'
      command: "--character-set-server=utf8 --collation-server=utf8_bin"

   - name:  Create zabbix server
     docker_container:
      image: zabbix/zabbix-server-mysql:latest
      name: '{{ CONTAINER_NAME_ZABBIX_SERVER }}'
      state: started
      env:
       DB_SERVER_HOST: '{{ CONTAINER_NAME_MY_SQL }}'
       MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
       MYSQL_USER: '{{ MYSQL_USER }}'
       MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
       MYSQL_ROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
      ports: 10051:10051
      networks:
       - name: '{{ ZABBIX_NETWORK_NAME }}'
         links: 
           - '{{ CONTAINER_NAME_MY_SQL }}:mysql'

   - name:  Create zabbix web server
     docker_container:
      image: zabbix/zabbix-web-nginx-mysql:latest
      name: '{{ CONTAINER_NAME_ZABBIX_WEB_SERVER }}'
      state: started
      env:
       DB_SERVER_HOST: '{{ CONTAINER_NAME_MY_SQL }}'
       MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
       MYSQL_USER: '{{ MYSQL_USER }}'
       MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
       MYSQL_ROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
      ports: 80:8080
      networks:
       - name: '{{ ZABBIX_NETWORK_NAME }}'
         links: 
           - '{{ CONTAINER_NAME_MY_SQL }}:mysql'
           - '{{ CONTAINER_NAME_ZABBIX_SERVER }}:zabbix-server'
    
   - name:  Create zabbix agent
     docker_container:
      image: zabbix/zabbix-agent:latest
      name: '{{ CONTAINER_NAME_ZABBIX_AGENT }}'
      state: started  
      env:
       ZBX_SERVER_HOST: '{{ CONTAINER_NAME_ZABBIX_SERVER }}'
      networks:
       - name: '{{ ZABBIX_NETWORK_NAME }}'
       